### ISSUE TITLE
Add all install requirements to setup.py

### ISSUE THREAD

**Issue by AndreasBackx** [selwin/python-user-agents#67]
In the readme it tells people to install pyyaml and ua-parser alongside this library. ua-parser seems to be included in the setup.py, but pyyaml is not. I'm up to make PR, but I don't know what the minimum required version for pyyaml. Could you add pyyaml to the setup.py and edit the readme?

**Comment by robcowie** [comment]
Pretty sure this is solved by https://github.com/selwin/python-user-agents/commit/9ad93b8f7972f1a7c3da237506afbf696e8447d7

**Comment by AndreasBackx** [comment]
@robcowie pyyaml still doesn't seem to be added which is why I created this issue. Unless the library no longer needs it?

**Comment by robcowie** [comment]
Ah I see. I'm pretty sure the readme is wrong. `pyyaml` isn't a requirement for this library and it's only a requirement for `ua-parser` during install (it's declared in `setup_requires`, https://github.com/ua-parser/uap-python/blob/master/setup.py#L186).

Certainly it seems to work in a fresh virtualenv for me without explicitly installing `pyyaml`. Can you confirm that?
